"""Writes the launcher icon (concept 1d, "Unrolling page", board 1 section 7)
as Android adaptive-icon vectors. Shapes are the board's, in its 144px
artboard; the visible 72dp of the 108dp adaptive canvas maps to it.

Run: python3 tool/make_icon.py   (then: flutter test tool/make_icon_png.dart)
"""
import math, os

RES = 'android/app/src/main/res'
PRIMARY, SURFACE, OUTLINE, CONTAINER = '#A15800', '#FEFBF9', '#DED8D1', '#FFDDC0'
S, O = 0.5, 18.0  # board px -> dp, inside the 108dp canvas


def rrect(x, y, w, h, tl, tr, br, bl):
    x, y, w, h = x * S + O, y * S + O, w * S, h * S
    tl, tr, br, bl = tl * S, tr * S, br * S, bl * S
    f = lambda v: f'{v:.2f}'.rstrip('0').rstrip('.')
    return (f'M{f(x + tl)},{f(y)} H{f(x + w - tr)} A{f(tr)},{f(tr)} 0 0 1 {f(x + w)},{f(y + tr)} '
            f'V{f(y + h - br)} A{f(br)},{f(br)} 0 0 1 {f(x + w - br)},{f(y + h)} '
            f'H{f(x + bl)} A{f(bl)},{f(bl)} 0 0 1 {f(x)},{f(y + h - bl)} '
            f'V{f(y + tl)} A{f(tl)},{f(tl)} 0 0 1 {f(x + tl)},{f(y)} Z')


# The page: 72x80 at (36,26), radii 10/10/4/4, three 8px lines (62%, 100%, 80%)
# inset 17 top / 13 sides with 9px gaps. The rolled foot: a 90x20 pill at (28,100).
page = rrect(36, 26, 72, 80, 10, 10, 4, 4)
inner = 72 - 26
lines = [rrect(49, 43 + i * 17, inner * w, 8, 4, 4, 4, 4) for i, w in enumerate((0.62, 1.0, 0.8))]
pill = rrect(28, 100, 90, 20, 10, 10, 10, 10)
page_c = ((36 + 36) * S + O, (26 + 40) * S + O)
pill_c = ((28 + 45) * S + O, (100 + 10) * S + O)


def group(c, body):
    return (f'    <group android:rotation="-6" android:pivotX="{c[0]:.2f}" android:pivotY="{c[1]:.2f}">\n'
            f'{body}    </group>\n')


def path(d, color, extra=''):
    return f'        <path android:fillColor="{color}"{extra} android:pathData="{d}" />\n'


def vector(body):
    return ('<?xml version="1.0" encoding="utf-8"?>\n'
            '<!-- Generated by tool/make_icon.py from the board\'s concept 1d. -->\n'
            '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
            '    android:width="108dp" android:height="108dp"\n'
            '    android:viewportWidth="108" android:viewportHeight="108">\n'
            f'{body}</vector>\n')


fg = group(page_c, path(page, SURFACE) + path(lines[0], PRIMARY) + path(lines[1], OUTLINE) + path(lines[2], OUTLINE))
fg += group(pill_c, path(pill, CONTAINER))
# Themed icons take one colour: the page with its lines cut out, and the foot.
mono = group(page_c, path(' '.join([page] + lines), '#FFFFFF', ' android:fillType="evenOdd"'))
mono += group(pill_c, path(pill, '#FFFFFF'))

os.makedirs(f'{RES}/mipmap-anydpi-v26', exist_ok=True)
open(f'{RES}/drawable/ic_launcher_foreground.xml', 'w').write(vector(fg))
open(f'{RES}/drawable/ic_launcher_monochrome.xml', 'w').write(vector(mono))
open(f'{RES}/values/ic_launcher_background.xml', 'w').write(
    '<?xml version="1.0" encoding="utf-8"?>\n<resources>\n'
    f'    <color name="ic_launcher_background">{PRIMARY}</color>\n</resources>\n')
adaptive = ('<?xml version="1.0" encoding="utf-8"?>\n'
            '<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">\n'
            '    <background android:drawable="@color/ic_launcher_background" />\n'
            '    <foreground android:drawable="@drawable/ic_launcher_foreground" />\n'
            '    <monochrome android:drawable="@drawable/ic_launcher_monochrome" />\n'
            '</adaptive-icon>\n')
open(f'{RES}/mipmap-anydpi-v26/ic_launcher.xml', 'w').write(adaptive)
print('ok')
