// Writes every launcher and splash asset for the v2 icon (concept C,
// "Bookmarked U") from lib/core/theme/launcher_icon.dart: the adaptive
// layers, the Android 12+ splash icon, the legacy mipmaps and the Play Store
// PNG. Run: flutter test tool/make_icon.dart
import 'dart:io';
import 'dart:ui' as ui;

import 'package:flutter/painting.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:unfurl/core/theme/launcher_icon.dart';

const String res = 'android/app/src/main/res';

String hex(Color c) => '#${c.toARGB32().toRadixString(16).padLeft(8, '0').toUpperCase()}';

/// The glyph as vector paths in a 108dp canvas whose 512 grid is scaled by
/// [scale] and offset by [inset] (the adaptive 72dp viewport sits at 18).
String vector({
  required double canvas,
  required double inset,
  required double scale,
  required String note,
  bool mono = false,
}) {
  final StringBuffer b = StringBuffer()
    ..writeln('<?xml version="1.0" encoding="utf-8"?>')
    ..writeln('<!-- v2 · V2-ICON, concept C. $note Generated by tool/make_icon.dart. -->')
    ..writeln('<vector xmlns:android="http://schemas.android.com/apk/res/android"')
    ..writeln('    android:width="${canvas.round()}dp" android:height="${canvas.round()}dp"')
    ..writeln('    android:viewportWidth="${canvas.round()}" android:viewportHeight="${canvas.round()}">')
    ..writeln(
      '    <group android:translateX="$inset" android:translateY="$inset" android:scaleX="$scale" android:scaleY="$scale">',
    );
  for (final GlyphLayer l in LauncherIcon.layers) {
    final String colour = mono ? '#FF000000' : hex(l.colour);
    final String alpha = mono && l.colour == LauncherIcon.mid
        ? ' android:strokeAlpha="${LauncherIcon.monoMidAlpha}"'
        : '';
    b
      ..writeln('        <path android:pathData="${l.d}"')
      ..writeln(
        l.filled
            ? '            android:fillColor="$colour" android:strokeColor="$colour"$alpha android:strokeWidth="${LauncherIcon.ribbonStroke.round()}" android:strokeLineJoin="round" />'
            : '            android:fillColor="#00000000" android:strokeColor="$colour"$alpha android:strokeWidth="${LauncherIcon.stroke.round()}" android:strokeLineCap="round" android:strokeLineJoin="round" />',
      );
  }
  b
    ..writeln('    </group>')
    ..writeln('</vector>');
  return b.toString();
}

/// The whole icon at [size] px; [rounded] clips to the board's rounded-square
/// mask (legacy launchers draw the PNG as is).
Future<List<int>> png(int size, {required bool rounded}) async {
  final ui.PictureRecorder rec = ui.PictureRecorder();
  final Canvas c = Canvas(rec);
  final double s = size.toDouble();
  if (rounded) c.clipRRect(RRect.fromRectAndRadius(Rect.fromLTWH(0, 0, s, s), Radius.circular(s * 92 / 512)));
  c.drawRect(Rect.fromLTWH(0, 0, s, s), Paint()..color = LauncherIcon.background);
  LauncherIcon.paint(c, s);
  final ui.Image image = await rec.endRecording().toImage(size, size);
  return (await image.toByteData(format: ui.ImageByteFormat.png))!.buffer.asUint8List();
}

void main() {
  test('write the launcher icon assets', () async {
    File('$res/drawable/ic_launcher_foreground.xml').writeAsStringSync(
      vector(
        canvas: 108,
        inset: 18,
        scale: 72 / 512,
        note: 'Adaptive foreground: 108dp canvas, the 512 grid on the 72dp viewport.',
      ),
    );
    File('$res/drawable/ic_launcher_monochrome.xml').writeAsStringSync(
      vector(
        canvas: 108,
        inset: 18,
        scale: 72 / 512,
        mono: true,
        note: 'Themed icon layer, alpha only; the system tints it.',
      ),
    );
    // Android 12+: 288dp canvas, glyph inside the 192dp circle (scale 0.43).
    File('$res/drawable/splash_icon.xml').writeAsStringSync(
      vector(
        canvas: 288,
        inset: (288 - 512 * 0.43) / 2,
        scale: 0.43,
        note: 'Splash icon: 288dp canvas, glyph in the 192dp circle.',
      ),
    );
    File('$res/drawable/ic_launcher_background.xml').writeAsStringSync('''
<?xml version="1.0" encoding="utf-8"?>
<!-- v2 · V2-ICON. Adaptive background. Generated by tool/make_icon.dart. -->
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="108dp" android:height="108dp"
    android:viewportWidth="108" android:viewportHeight="108">
    <path android:pathData="M0,0h108v108h-108z" android:fillColor="${hex(LauncherIcon.background)}" />
</vector>
''');
    for (final (String density, int px) in <(String, int)>[
      ('mdpi', 48),
      ('hdpi', 72),
      ('xhdpi', 96),
      ('xxhdpi', 144),
      ('xxxhdpi', 192),
    ]) {
      File('$res/mipmap-$density/ic_launcher.png').writeAsBytesSync(await png(px, rounded: true));
    }
    Directory('docs/store').createSync(recursive: true);
    File('docs/store/play-store-512.png').writeAsBytesSync(await png(512, rounded: false));
  });
}
